version: '2.0'
services:

  db:
    image: postgres
    restart: always
    environment:
      # POSTGRES_DB: mydb
      POSTGRES_PASSWORD: qwerty
    networks:
     - net_123

  adminer:
    image: adminer
    restart: always
    networks:
     - net_123

  receive:
    build: ./rec_test
    depends_on:
     - db
     - adminer
     - send
    networks:
     - net_123
    depends_on:
     - rabbit
     - send

  send:
    build: ./send_test
    networks:
     - net_123
    depends_on:
     - rabbit
     - db
     - adminer


  rabbit:
    image: rabbitmq
    networks:
     - net_123


networks:
 net_123:
