version: '2.0'
services:

  db:
    image: postgres
    restart: always
    environment:
      # POSTGRES_DB: mydb
      POSTGRES_PASSWORD: qwerty
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - net_123

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - net_123

  receive:
    build: ./rec_test
    volumes:
      - ./rec_test:/code
    links:
      - db
      - rabbit
      - adminer
    depends_on:
      - db
      - adminer
      - rabbit
    networks:
      - net_123

  rabbit:
    image: rabbitmq
    networks:
      - net_123

networks:
 net_123:
